# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sayhi_pb2 as sayhi__pb2


class GreeterStub(object):
  """服务定义
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHi = channel.unary_unary(
        '/demo.Greeter/SayHi',
        request_serializer=sayhi__pb2.HiRequest.SerializeToString,
        response_deserializer=sayhi__pb2.HiReply.FromString,
        )


class GreeterServicer(object):
  """服务定义
  """

  def SayHi(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHi': grpc.unary_unary_rpc_method_handler(
          servicer.SayHi,
          request_deserializer=sayhi__pb2.HiRequest.FromString,
          response_serializer=sayhi__pb2.HiReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'demo.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
